apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "hello-world.fullname" . }}
  labels:
    {{- include "hello-world.labels" . | nindent 4 }}
spec:
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          name: ingress
    ports:
    - port: {{ .Values.service.port }}
      protocol: TCP
  - from:
    - namespaceSelector:
        matchLabels:
          name: {{ .Release.Namespace }}
    ports:
    - port: {{ .Values.service.port }}
      protocol: TCP
  podSelector:
    matchLabels:
      {{- include "hello-world.selectorLabels" . | nindent 6 }}
  policyTypes:
  - Ingress
